apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-grampsweb-data
  namespace: grampsweb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: app-grampsweb-data
  storageClassName: ""
