apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    metrics:
      prometheus:
        entryPoint: metrics
    ports:
      metrics:
        port: 9100
        expose:
          default: false
        protocol: TCP
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
