controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/slskd/slskd
          tag: latest
        env:
          SLSKD_APP_DIR: /config
          SLSKD_DOWNLOADS_DIR: /downloads
          SLSKD_SLSK_LISTEN_PORT: "2234"
          SLSKD_REMOTE_CONFIGURATION: "true"
        envFrom:
          - secretRef:
              name: slskd-credentials

service:
  main:
    controller: main
    ports:
      http:
        port: 5030
  soulseek:
    controller: main
    type: LoadBalancer
    ports:
      soulseek:
        port: 2234
        protocol: TCP

ingress:
  main:
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - host: slskd.wfink.cc
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - secretName: slskd-tls
        hosts:
          - slskd.wfink.cc

persistence:
  config:
    type: persistentVolumeClaim
    existingClaim: app-slskd-config
    globalMounts:
      - path: /config
  downloads:
    type: persistentVolumeClaim
    existingClaim: music-ingest
    globalMounts:
      - path: /downloads
