persistence:
  enabled: true
  storageClass: "local"
  accessMode: ReadWriteOnce
  size: 10Gi

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: memos.wfink.cc
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: memos-tls
      hosts:
        - memos.wfink.cc
