apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-data
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: https://github.com/wfinken/k8sconfig
      targetRevision: HEAD
      path: manifests/app-data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
