apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grampsweb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: grampsweb
  sources:
    - repoURL: oci://codeberg.org/wrenix/helm-charts
      chart: grampsweb
      targetRevision: 0.2.45
      helm:
        releaseName: grampsweb
        valueFiles:
          - $values/grampsweb/values.yaml
    - repoURL: https://github.com/wfinken/k8sconfig
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/wfinken/k8sconfig
      targetRevision: HEAD
      path: manifests/grampsweb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
