apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: https://haproxytech.github.io/helm-charts
      chart: kubernetes-ingress
      targetRevision: 1.49.0
      helm:
        releaseName: kubernetes-ingress-1777830932
        valueFiles:
          - $values/haproxy-ingress/values.yaml
    - repoURL: https://github.com/wfinken/k8sconfig
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
