apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: priority-classes
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wfinken/k8sconfig.git
    targetRevision: HEAD
    path: manifests/priority-classes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
