apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: privatebin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: privatebin
  sources:
    - repoURL: https://privatebin.github.io/helm-chart
      chart: privatebin
      targetRevision: 0.23.4
      helm:
        releaseName: privatebin
        valueFiles:
          - $values/privatebin/values.yaml
    - repoURL: https://github.com/wfinken/k8sconfig
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
