# apps/technitium.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: technitium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.obeone.cloud
    targetRevision: 1.10.0
    chart: technitium-dnsserver
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/wfinken/k8sconfig/main/technitium/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: technitium
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
