# apps/technitium.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: technitium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.obeone.cloud
      chart: technitium-dnsserver
      targetRevision: 1.10.0
      helm:
        valueFiles:
          - $values/technitium/values.yaml
    - repoURL: https://github.com/wfinken/k8sconfig.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: technitium
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
