apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-privatebin-data
  namespace: privatebin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: app-privatebin-data
  storageClassName: ""
