apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-music
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs-music
    volumeAttributes:
      server: 172.22.0.1
      share: /Volumes/Storage/Media/Music
      mountOptions: nfsvers=4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-music-library
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs-music-library
    volumeAttributes:
      server: 172.22.0.1
      share: /Volumes/Storage/Media/Music/library
      mountOptions: nfsvers=4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-music-ingest
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs-music-ingest
    volumeAttributes:
      server: 172.22.0.1
      share: /Volumes/Storage/Media/Music/ingest
      mountOptions: nfsvers=4
